name: Security Tests

on:
  pull_request:
    branches:
      - '**'

permissions:
  checks: write
  contents: read

jobs:
  security-tests:
    runs-on: ubuntu-latest
    env:
      BRIGHT_TARGET_URL: http://127.0.0.1:8585
      BRIGHT_HOSTNAME: ${{ vars.BRIGHT_HOSTNAME }}
      BRIGHT_PROJECT_ID: ${{ vars.BRIGHT_PROJECT_ID }}
      BRIGHT_TOKEN: ${{ secrets.BRIGHT_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install Go dependencies
      run: |
        go mod download

    - name: Install SecTester dependencies
      working-directory: .brightsec
      run: npm i --save=false @sectester/core @sectester/repeater @sectester/scan @sectester/runner

    - name: Start application
      run: |
        nohup go run main.go &
        sleep 5

    - name: Wait for application to be ready
      run: |
        until nc -zv 127.0.0.1 8585; do
          echo "Waiting for application to start..."
          sleep 2
        done

    - name: Run security tests
      run: |
        node --experimental-transform-types --experimental-strip-types --experimental-detect-module \
        --disable-warning=MODULE_TYPELESS_PACKAGE_JSON --disable-warning=ExperimentalWarning \
        --test-force-exit --test .brightsec/tests/*.test.ts --test-concurrency=4
